# actionlint configuration
# Suppress warnings from external dependencies (submodules)

ignore:
  # Ignore all workflows in oh-my-zsh submodule
  - 'packages/zsh/.oh-my-zsh/.github/workflows/.*'





