# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint#rules--aliases

# MD001 - Heading levels should only increment by one level at a time
MD001: true

# MD003 - Heading style should be consistent throughout the document
MD003:
  style: "atx"

# MD004 - Unordered list style should be consistent
MD004:
  style: "dash"

# MD007 - Unordered list indentation should be consistent
MD007:
  indent: 2

# MD013 - Line length should be within the specified limit
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# MD022 - Headings should be surrounded by blank lines
MD022: true

# MD024 - Multiple headers with the same content
MD024: true

# MD025 - Multiple top level headers in the same document
MD025: true

# MD029 - Ordered list item prefix should be consistent
MD029:
  style: "ordered"

# MD033 - Inline HTML should be allowed for specific elements
MD033: true

# MD041 - First line in file should be a top level heading
MD041: true
