name: Validate Dotfiles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Install linting tools
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        npm install -g markdownlint-cli
    
    - name: Lint Markdown files
      run: |
        markdownlint "**/*.md" --ignore node_modules
    
    - name: Lint Bash scripts
      run: |
        shellcheck "**/*.sh" dot --exclude=SC1090,SC1091

  validate-ubuntu:
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y stow git tmux zsh
    
    - name: Validate installation
      run: |
        cd ${{ github.workspace }}
        chmod +x dot
        echo "HOME: $HOME"
        echo "Workspace: ${{ github.workspace }}"
        ls -la $HOME/.git* $HOME/.zshrc $HOME/.tmux.conf 2>/dev/null || echo "Files not found in HOME"
        ./dot install
    
    - name: Run validation
      run: |
        cd ${{ github.workspace }}
        ./dot validate
    
    - name: Test shell configuration
      run: |
        zsh -c "source ~/.zshrc && echo 'Zsh configuration loaded successfully'"
    
    - name: Test git configuration
      run: |
        git config --global user.name "Test User"
        git config --global user.email "test@example.com"
        git config --global --list | grep -q "user.name=Test User"
        git config --global --list | grep -q "user.email=test@example.com"

  validate-macos:
    runs-on: macos-latest
    needs: lint
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Install dependencies
      run: |
        brew install stow git tmux zsh
    
    - name: Validate installation
      run: |
        cd ${{ github.workspace }}
        chmod +x dot
        echo "HOME: $HOME"
        echo "Workspace: ${{ github.workspace }}"
        ls -la $HOME/.git* $HOME/.zshrc $HOME/.tmux.conf 2>/dev/null || echo "Files not found in HOME"
        ./dot install
    
    - name: Run validation
      run: |
        cd ${{ github.workspace }}
        ./dot validate
    
    - name: Test shell configuration
      run: |
        zsh -c "source ~/.zshrc && echo 'Zsh configuration loaded successfully'"
    
    - name: Test git configuration
      run: |
        git config --global user.name "Test User"
        git config --global user.email "test@example.com"
        git config --global --list | grep -q "user.name=Test User"
        git config --global --list | grep -q "user.email=test@example.com"
