name: Validate Dotfiles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Install linting tools and run linting
      run: |
        sudo apt-get install -y shellcheck
        npm install -g markdownlint-cli
        markdownlint "**/*.md" --ignore node_modules
        shellcheck dot

  validate-ubuntu:
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Install dependencies
      run: |
        sudo apt-get install -y stow git tmux zsh
    
    - name: Validate installation
      run: |
        cd ${{ github.workspace }}
        chmod +x dot
        ./dot install
        ./dot validate
    
    - name: Test configurations
      run: |
        zsh -c "source ~/.zshrc && echo 'Zsh configuration loaded successfully'"
        git config --global user.name "Test User"
        git config --global user.email "test@example.com"
        git config --global --list | grep -q "user.name=Test User"
        git config --global --list | grep -q "user.email=test@example.com"

  validate-macos:
    runs-on: macos-latest
    needs: lint
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Install dependencies
      run: |
        brew install stow git tmux zsh
    
    - name: Validate installation
      run: |
        cd ${{ github.workspace }}
        chmod +x dot
        ./dot install
        ./dot validate
    
    - name: Test configurations
      run: |
        zsh -c "source ~/.zshrc && echo 'Zsh configuration loaded successfully'"
        git config --global user.name "Test User"
        git config --global user.email "test@example.com"
        git config --global --list | grep -q "user.name=Test User"
        git config --global --list | grep -q "user.email=test@example.com"
